// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAUn4Th7z4uHUIsHLjWJz_jX65Vx7JdysE',
    appId: '1:427631997466:web:04d3eb803315d8c0f457a3',
    messagingSenderId: '427631997466',
    projectId: 'smart-delivery-collection',
    authDomain: 'smart-delivery-collection.firebaseapp.com',
    storageBucket: 'smart-delivery-collection.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2k7zSO0cBpPSkjNkKwf9qFBShpQPFhrE',
    appId: '1:427631997466:android:5c1ec004d5d4c765f457a3',
    messagingSenderId: '427631997466',
    projectId: 'smart-delivery-collection',
    storageBucket: 'smart-delivery-collection.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBuClJRb94FIIJ6SvX1qqYUSK2Glrs4haY',
    appId: '1:427631997466:ios:7a9c8eae065bbca3f457a3',
    messagingSenderId: '427631997466',
    projectId: 'smart-delivery-collection',
    storageBucket: 'smart-delivery-collection.firebasestorage.app',
    iosBundleId: 'com.example.smartDelivery',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBuClJRb94FIIJ6SvX1qqYUSK2Glrs4haY',
    appId: '1:427631997466:ios:7a9c8eae065bbca3f457a3',
    messagingSenderId: '427631997466',
    projectId: 'smart-delivery-collection',
    storageBucket: 'smart-delivery-collection.firebasestorage.app',
    iosBundleId: 'com.example.smartDelivery',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAUn4Th7z4uHUIsHLjWJz_jX65Vx7JdysE',
    appId: '1:427631997466:web:d0a859f8b375c911f457a3',
    messagingSenderId: '427631997466',
    projectId: 'smart-delivery-collection',
    authDomain: 'smart-delivery-collection.firebaseapp.com',
    storageBucket: 'smart-delivery-collection.firebasestorage.app',
  );
}
